repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -  id: check-yaml
      -  id: trailing-whitespace
      -  id: check-json

  - repo: https://github.com/psf/black
    rev: 20.8b1 # https://github.com/psf/black/tags
    hooks:
      - id: black
        args: ["-v"]
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
