version: '3.7'
services:
  sms:
    hostname: cons2-sms
    image: lnlscon/notification:2019-03-22
    #image: itorafael/cons2-sms:v0.3
    #image: cons2-sms
    #ports:
    #  - "465"
    #  - "587"
    networks:
      hostnet: {}
    dns:
      - 10.0.0.71
      - 10.0.0.72
    environment:
      - CONS2_SMS_PASSWD=${CONS2_SMS_PASSWD}
    deploy:
    #  placement:
    #    constraints:
    #      - node.hostname == LA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  hostnet:
    external: true
    name: host
