version: "3.7"
services:
  mongo:
    image: mongo:4.4.1
    ports:
      - 27017:27017

  sms:
    image: lnlscon/notification:v2.0
    build: .
    network_mode: host
    secrets:
      - CONS2_SMS_PASSWD
    volumes:
      - ./SMS_LOGIN:/run/secrets/SMS_LOGIN
      - ./SMS_PASSWORD:/run/secrets/SMS_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

secrets:
  CONS2_SMS_PASSWD:
    external: true
