version: '3.7'
services:
  sms:
    image: lnlscon/notification:2019-06-04
    volumes:
      - /home/con-srv/LA-disk0/misc-brick/repository/mailpy/app:/app
    #ports:
    #  - "465"
    #  - "587"
    networks:
      hostnet: {}
    dns:
      - 10.0.0.71
      - 10.0.0.72
    #environment:
    #  - CONS2_SMS_PASSWD=${CONS2_SMS_PASSWD}
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
        condition: on-failure
    secrets:
      - CONS2_SMS_PASSWD
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

secrets:
  CONS2_SMS_PASSWD:
    external: true

networks:
  hostnet:
    external: true
    name: host
