version: 1
formatters:
  simple:
    format: '%(name)s %(threadName)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  SMS:
    level: DEBUG
    handlers: [console]
    propagate: no
  IOC:
    level: DEBUG
    handlers: [console]
    propagate: no
  COMMONS:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]